/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in typical app scaffolds.
// It is committed here so TypeScript-aware editors work from a fresh clone.
